version: "3.9"
services:
  backend:
    build: ./backend
    volumes: ["./backend/app:/code/app"]
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [mongo]
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
volumes:
  mongo_data:
